#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Build beginner-friendly API references from committed OpenAPI snapshots."""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import sys
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = ROOT / "spec"
NOTES_DIR = ROOT / "notes"
FACTS_PATH = ROOT / "tools" / "facts.json"

GATEWAY_HOST = "https://iterogatewayapi.azurewebsites.net"
PRACTICE_HOST = "https://iteropracticeapi.azurewebsites.net"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
METHOD_ORDER = {method: index for index, method in enumerate(HTTP_METHODS)}
EXPECTED_OPERATION_COUNT = 51
GENERATED_HEADER = "<!-- GENERATED by tools/build-refs.py — edit {note} -->"

EXPECTED_FACT_IDS = {
    "fact:pagination-zero-indexed",
    "fact:evaluation-host-exception",
    "fact:scorecard-publish-api",
    "fact:persona-voiceid",
    "fact:context-safety-projection",
    "fact:tenantuserid-not-id",
    "fact:user-write-owner-role",
    "fact:get-users-alias",
    "fact:auth-header",
    "fact:tags-autocreate",
    "fact:calltags-substring-match",
}


class ReferenceBuildError(RuntimeError):
    """Raised when a source or generated reference fails a drift gate."""


@dataclass(frozen=True)
class OutputConfig:
    """Describe one generated reference and its hand-maintained notes source."""

    key: str
    title: str
    path: Path
    note_path: Path


@dataclass(frozen=True)
class Operation:
    """Hold the structural data for one OpenAPI operation."""

    spec_name: str
    document: dict[str, Any]
    path: str
    method: str
    path_item: dict[str, Any]
    definition: dict[str, Any]


@dataclass(frozen=True)
class SchemaRow:
    """Represent one field in a request or response schema table."""

    field: str
    type_name: str
    required: bool | None
    nullable: bool | None
    allowed_values: str


OUTPUTS = {
    "personas": OutputConfig(
        key="personas",
        title="Personas API reference",
        path=ROOT / "skills/personas/references/personas.md",
        note_path=NOTES_DIR / "personas.md",
    ),
    "scenarios": OutputConfig(
        key="scenarios",
        title="Practice scenarios API reference",
        path=ROOT / "skills/scenarios/references/scenarios.md",
        note_path=NOTES_DIR / "scenarios.md",
    ),
    "scorecards": OutputConfig(
        key="scorecards",
        title="Scorecards API reference",
        path=ROOT / "skills/scorecards/references/scorecards.md",
        note_path=NOTES_DIR / "scorecards.md",
    ),
    "learning-paths": OutputConfig(
        key="learning-paths",
        title="Learning paths API reference",
        path=ROOT / "skills/learning-paths/references/learning-paths.md",
        note_path=NOTES_DIR / "learning-paths.md",
    ),
    "manage-users": OutputConfig(
        key="manage-users",
        title="Users API reference",
        path=ROOT / "skills/manage-users/references/users.md",
        note_path=NOTES_DIR / "users.md",
    ),
    "upload-users": OutputConfig(
        key="upload-users",
        title="CSV user import API reference",
        path=ROOT / "skills/upload-users/references/upload-users.md",
        note_path=NOTES_DIR / "users.md",
    ),
    "conversations": OutputConfig(
        key="conversations",
        title="Conversations and evaluations API reference",
        path=ROOT / "skills/conversations/references/conversations.md",
        note_path=NOTES_DIR / "conversations.md",
    ),
}


# Each canonical table is compared with the union of its matching component
# schemas. Source is an alias for the API's ConversationIntegrationType enum.
ENUM_COMPONENT_PATTERNS: dict[str, tuple[str, ...]] = {
    "CallType": ("CallType",),
    "ConversationStatus": ("ConversationStatus",),
    "Source": ("ConversationIntegrationType",),
    "ConversationIntegrationType": ("ConversationIntegrationType",),
    "InteractionType": ("InteractionType",),
    "ScorecardType": ("ScorecardType",),
    "EvaluationStatus": ("EvaluationStatus",),
    "RubrikScale": ("RubrikScale",),
    "ScorecardTemplateStatus": ("ScorecardTemplateStatus",),
    "PersonaType": ("PersonaType",),
    "PracticeScenarioType": ("PracticeScenarioType",),
    "ScorecardAppliedStatus": ("PublicScorecardAppliedStatus",),
}

FIELD_ENUM_NAMES = {
    "calltype": "CallType",
    "calltypes": "CallType",
    "conversationstatus": "ConversationStatus",
    "conversationstatuses": "ConversationStatus",
    "source": "ConversationIntegrationType",
    "interactiontype": "InteractionType",
    "evaluationtype": "ScorecardType",
    "scorecardtype": "ScorecardType",
    "evaluationstatus": "EvaluationStatus",
    "rubrikscale": "RubrikScale",
    "overallrubrikscale": "RubrikScale",
    "personatype": "PersonaType",
    "practicescenariotype": "PracticeScenarioType",
    "scorecardappliedstatus": "ScorecardAppliedStatus",
}

# These read operations can return collections or transcript-sized payloads. Keep
# their worked examples out of the agent's context by writing the raw response to
# a predictable local file. Users can then project only the fields they need.
SAFE_OUTPUT_FILES = {
    ("get", "/api/public/v1/agent"): "agents.json",
    ("get", "/api/public/v1/get-user-groups"): "user-groups.json",
    ("get", "/api/public/v1/learning-path"): "learning-paths.json",
    ("get", "/api/public/v1/persona"): "personas.json",
    ("get", "/api/public/v1/persona/voices"): "persona-voices.json",
    ("get", "/api/public/v1/practice-scenario"): "practice-scenarios.json",
    ("get", "/api/public/v1/practice-scenario/call-types"): "call-types.json",
    (
        "get",
        "/api/public/v1/practice-scenario/communication-styles",
    ): "communication-styles.json",
    ("get", "/api/public/v1/scorecard"): "scorecards.json",
    ("get", "/api/public/v1/scorecard-category"): "scorecard-categories.json",
    ("get", "/api/public/v1/scorecard-criteria"): "scorecard-criteria.json",
    ("get", "/api/public/v1/scorecard-criteria/rubrics"): "rubrics.json",
    ("get", "/api/public/v1/user"): "users.json",
    ("get", "/api/public/v1/call/get-call"): "call.json",
    ("post", "/api/public/v1/call/get-calls"): "calls-page.json",
    (
        "get",
        "/api/public/v1/call/scorecard-templates",
    ): "evaluable-scorecards.json",
}

ERROR_MEANINGS = {
    "400": "The request failed validation. Check field names, types, and values.",
    "401": "The API key is missing or invalid.",
    "403": "The API key does not have permission for this operation.",
    "404": "The requested resource was not found.",
    "405": "The HTTP method is not allowed for this path.",
    "409": "The request conflicts with the resource's current state.",
    "422": "The server could not process one or more supplied fields.",
    "429": "Too many requests were sent. Wait before retrying.",
    "500": "The service returned an internal error.",
    "502": "The gateway received an invalid upstream response.",
    "503": "The service is temporarily unavailable.",
    "504": "The gateway timed out waiting for the service.",
    "default": "The request returned an error response.",
}


def relative(path: Path) -> str:
    """Return a stable repository-relative POSIX path."""
    return path.resolve().relative_to(ROOT).as_posix()


def load_json(path: Path) -> Any:
    """Read JSON and turn parse or I/O failures into concise build errors."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ReferenceBuildError(f"missing required source: {relative(path)}") from exc
    except OSError as exc:
        raise ReferenceBuildError(f"could not read {relative(path)}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ReferenceBuildError(
            f"invalid JSON in {relative(path)} at line {exc.lineno}: {exc.msg}"
        ) from exc


def read_text(path: Path) -> str:
    """Read a UTF-8 source file with a concise error on failure."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ReferenceBuildError(f"missing required source: {relative(path)}") from exc
    except OSError as exc:
        raise ReferenceBuildError(f"could not read {relative(path)}: {exc}") from exc


def load_specs() -> dict[str, dict[str, Any]]:
    """Load and validate the three committed OpenAPI 3.0.1 snapshots."""
    documents: dict[str, dict[str, Any]] = {}
    for name in ("practice.json", "talk-track.json", "tenant.json"):
        path = SPEC_DIR / name
        document = load_json(path)
        if not isinstance(document, dict):
            raise ReferenceBuildError(f"{relative(path)} must contain a JSON object")
        if document.get("openapi") != "3.0.1":
            raise ReferenceBuildError(
                f"{relative(path)} has OpenAPI {document.get('openapi')!r}; expected '3.0.1'"
            )
        if not isinstance(document.get("paths"), dict):
            raise ReferenceBuildError(f"{relative(path)} is missing a paths object")
        components = document.get("components")
        if not isinstance(components, dict) or not isinstance(
            components.get("schemas"), dict
        ):
            raise ReferenceBuildError(f"{relative(path)} is missing components.schemas")
        documents[name] = document
    return documents


def extract_marked_block(source: str, marker: str, path: Path) -> str | None:
    """Extract one complete notes block, preserving its marker comments."""
    pattern = re.compile(
        rf"^[ \t]*<!--\s*{re.escape(marker)}\s*-->\s*$.*?"
        rf"^[ \t]*<!--\s*/{re.escape(marker)}\s*-->\s*$",
        flags=re.MULTILINE | re.DOTALL,
    )
    matches = list(pattern.finditer(source))
    if len(matches) > 1:
        raise ReferenceBuildError(
            f"{relative(path)} contains more than one {marker!r} notes block"
        )
    if not matches:
        return None
    return matches[0].group(0).strip()


def parse_enum_tables(shared_notes: str) -> dict[str, dict[int, str]]:
    """Parse integer-valued enum tables below level-three Markdown headings."""
    lines = shared_notes.splitlines()
    parsed: dict[str, dict[int, str]] = {}

    for index, line in enumerate(lines):
        heading = re.match(r"^###\s+(.+?)\s*$", line)
        if not heading:
            continue
        name = heading.group(1).strip().strip("`")
        if name not in ENUM_COMPONENT_PATTERNS:
            continue

        values: dict[int, str] = {}
        for candidate in lines[index + 1 :]:
            if re.match(r"^#{1,3}\s+", candidate):
                break
            if not candidate.lstrip().startswith("|"):
                continue
            cells = [
                cell.strip().strip("`")
                for cell in candidate.strip().strip("|").split("|")
            ]
            if not cells:
                continue
            try:
                value = int(cells[0], 10)
            except ValueError:
                continue
            label = cells[1].strip().strip("`") if len(cells) > 1 else str(value)
            if value in values:
                raise ReferenceBuildError(
                    f"notes/_shared.md enum {name} repeats value {value}"
                )
            values[value] = label

        if not values:
            raise ReferenceBuildError(
                f"notes/_shared.md enum {name} has no integer-valued rows"
            )
        if name in parsed:
            raise ReferenceBuildError(
                f"notes/_shared.md contains more than one enum table named {name}"
            )
        parsed[name] = values

    missing = sorted(set(ENUM_COMPONENT_PATTERNS) - set(parsed))
    if missing:
        raise ReferenceBuildError(
            "notes/_shared.md is missing canonical enum table(s): " + ", ".join(missing)
        )
    return parsed


def short_component_name(component_name: str) -> str:
    """Return the readable final segment of a fully qualified schema name."""
    final = component_name.rsplit(".", 1)[-1]
    if ("`" in final or "[[" in final) and "PagedModel" in final:
        return "PagedResult"
    return final


def canonical_enum_for_component(component_name: str) -> str | None:
    """Map a component name to a hand-authored canonical enum table."""
    short_name = short_component_name(component_name)
    for canonical, patterns in ENUM_COMPONENT_PATTERNS.items():
        if canonical == "Source":
            continue
        if short_name in patterns:
            return canonical
    return None


def validate_enum_tables(
    specs: Mapping[str, dict[str, Any]], enum_tables: Mapping[str, Mapping[int, str]]
) -> None:
    """Require exact equality between each canonical table and schema union."""
    schema_unions: dict[str, set[int]] = {
        name: set() for name in ENUM_COMPONENT_PATTERNS
    }

    for document in specs.values():
        for component_name, schema in document["components"]["schemas"].items():
            if not isinstance(schema, dict) or "enum" not in schema:
                continue
            short_name = short_component_name(component_name)
            for canonical, patterns in ENUM_COMPONENT_PATTERNS.items():
                if short_name not in patterns:
                    continue
                raw_values = schema.get("enum")
                if not isinstance(raw_values, list) or not all(
                    isinstance(value, int) and not isinstance(value, bool)
                    for value in raw_values
                ):
                    raise ReferenceBuildError(
                        f"schema enum {component_name} must contain only integers"
                    )
                schema_unions[canonical].update(raw_values)

    errors: list[str] = []
    for canonical in ENUM_COMPONENT_PATTERNS:
        note_values = set(enum_tables[canonical])
        schema_values = schema_unions[canonical]
        if not schema_values:
            errors.append(f"enum {canonical}: no matching schema occurrence")
            continue
        missing_from_notes = sorted(schema_values - note_values)
        absent_from_schemas = sorted(note_values - schema_values)
        details: list[str] = []
        if missing_from_notes:
            details.append(f"missing from notes: {missing_from_notes}")
        if absent_from_schemas:
            details.append(f"absent from schema union: {absent_from_schemas}")
        if details:
            errors.append(f"enum {canonical}: " + "; ".join(details))

    if errors:
        raise ReferenceBuildError("enum validation failed:\n- " + "\n- ".join(errors))


def safe_repo_path(raw_path: str, *, source: str) -> Path:
    """Resolve a manifest path and reject paths outside the repository."""
    candidate = (ROOT / raw_path).resolve()
    try:
        candidate.relative_to(ROOT)
    except ValueError as exc:
        raise ReferenceBuildError(
            f"{source} points outside the repository: {raw_path}"
        ) from exc
    return candidate


def load_and_validate_facts() -> list[dict[str, Any]]:
    """Validate the fact manifest and require each marker in its notes source."""
    manifest = load_json(FACTS_PATH)
    if not isinstance(manifest, dict) or not isinstance(manifest.get("facts"), list):
        raise ReferenceBuildError("tools/facts.json must contain a facts array")

    facts: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, raw_fact in enumerate(manifest["facts"]):
        location = f"tools/facts.json facts[{index}]"
        if not isinstance(raw_fact, dict):
            raise ReferenceBuildError(f"{location} must be an object")
        fact_id = raw_fact.get("id")
        notes = raw_fact.get("notes")
        outputs = raw_fact.get("outputs")
        if not isinstance(fact_id, str) or not fact_id.startswith("fact:"):
            raise ReferenceBuildError(f"{location}.id must start with 'fact:'")
        if fact_id in seen:
            raise ReferenceBuildError(f"tools/facts.json repeats marker {fact_id}")
        if not isinstance(notes, str):
            raise ReferenceBuildError(f"{location}.notes must be a path string")
        if (
            not isinstance(outputs, list)
            or not outputs
            or not all(isinstance(output, str) for output in outputs)
        ):
            raise ReferenceBuildError(
                f"{location}.outputs must be a non-empty path list"
            )

        note_path = safe_repo_path(notes, source=location)
        marker = f"<!-- {fact_id} -->"
        if marker not in read_text(note_path):
            raise ReferenceBuildError(
                f"missing marker {fact_id} in notes source {notes}"
            )

        for output in outputs:
            output_path = safe_repo_path(output, source=location)
            if output_path not in {
                config.path.resolve() for config in OUTPUTS.values()
            }:
                raise ReferenceBuildError(
                    f"{location} names unmanaged generated output {output}"
                )

        seen.add(fact_id)
        facts.append(raw_fact)

    missing = sorted(EXPECTED_FACT_IDS - seen)
    unexpected = sorted(seen - EXPECTED_FACT_IDS)
    if missing or unexpected:
        details: list[str] = []
        if missing:
            details.append("missing " + ", ".join(missing))
        if unexpected:
            details.append("unexpected " + ", ".join(unexpected))
        raise ReferenceBuildError(
            "tools/facts.json must list the 11 verified facts exactly: "
            + "; ".join(details)
        )
    return facts


def classify_operation(method: str, path: str) -> tuple[str | None, str | None]:
    """Route one API operation to a skill, or name its deliberate suppression."""
    if method == "get" and path == "/api/public/v1/get-users":
        return None, "canonical-user-alias"
    if path.startswith("/api/public/v1/persona"):
        return "personas", None
    if path.startswith("/api/public/v1/practice-scenario"):
        return "scenarios", None
    if path.startswith("/api/public/v1/scorecard"):
        return "scorecards", None
    if path == "/api/public/v1/agent":
        return "scorecards", None
    if path.startswith("/api/public/v1/learning-path"):
        return "learning-paths", None
    if path == "/api/public/v1/get-user-groups":
        return "manage-users", None
    if path == "/api/public/v1/user/import-csv":
        return "upload-users", None
    if path.startswith("/api/public/v1/user"):
        return "manage-users", None
    if path.startswith(
        (
            "/api/public/v1/call",
            "/api/public/v1/call-tag",
            "/api/public/v1/evaluation",
        )
    ):
        return "conversations", None
    return None, None


def collect_operations(
    specs: Mapping[str, dict[str, Any]],
) -> tuple[dict[str, list[Operation]], list[tuple[str, str]]]:
    """Collect every supported method and require an explicit routing decision."""
    grouped = {key: [] for key in OUTPUTS}
    suppressed: list[tuple[str, str]] = []
    unmapped: list[str] = []
    operation_count = 0

    for spec_name, document in specs.items():
        for path, raw_path_item in document["paths"].items():
            if not isinstance(raw_path_item, dict):
                raise ReferenceBuildError(f"{spec_name} path {path} must be an object")
            for method in HTTP_METHODS:
                if method not in raw_path_item:
                    continue
                definition = raw_path_item[method]
                if not isinstance(definition, dict):
                    raise ReferenceBuildError(
                        f"{spec_name} operation {method.upper()} {path} must be an object"
                    )
                operation_count += 1
                key, reason = classify_operation(method, path)
                if key is None and reason is not None:
                    suppressed.append((method, path))
                    continue
                if key is None:
                    unmapped.append(f"{method.upper()} {path} ({spec_name})")
                    continue
                grouped[key].append(
                    Operation(
                        spec_name=spec_name,
                        document=document,
                        path=path,
                        method=method,
                        path_item=raw_path_item,
                        definition=definition,
                    )
                )

    if unmapped:
        raise ReferenceBuildError(
            "unmapped OpenAPI operations:\n- " + "\n- ".join(sorted(unmapped))
        )
    if operation_count != EXPECTED_OPERATION_COUNT:
        raise ReferenceBuildError(
            f"expected {EXPECTED_OPERATION_COUNT} OpenAPI operations, found {operation_count}; "
            "review resource routing before accepting the snapshot"
        )
    if suppressed != [("get", "/api/public/v1/get-users")]:
        rendered = ", ".join(f"{method.upper()} {path}" for method, path in suppressed)
        raise ReferenceBuildError(
            "the only suppressed operation must be the verified canonical user alias; "
            f"found: {rendered or 'none'}"
        )

    for operations in grouped.values():
        operations.sort(key=lambda op: (op.path, METHOD_ORDER[op.method]))
    return grouped, suppressed


def resolve_schema(
    document: Mapping[str, Any], schema: Mapping[str, Any]
) -> dict[str, Any]:
    """Resolve one local components.schemas reference."""
    reference = schema.get("$ref")
    if reference is None:
        return dict(schema)
    prefix = "#/components/schemas/"
    if not isinstance(reference, str) or not reference.startswith(prefix):
        raise ReferenceBuildError(f"unsupported schema reference: {reference!r}")
    component_name = reference.removeprefix(prefix)
    try:
        target = document["components"]["schemas"][component_name]
    except KeyError as exc:
        raise ReferenceBuildError(f"schema reference not found: {reference}") from exc
    if not isinstance(target, dict):
        raise ReferenceBuildError(f"schema reference is not an object: {reference}")
    return target


def referenced_component(schema: Mapping[str, Any]) -> str | None:
    """Return a local component name when schema is a component reference."""
    reference = schema.get("$ref")
    prefix = "#/components/schemas/"
    if isinstance(reference, str) and reference.startswith(prefix):
        return reference.removeprefix(prefix)
    return None


def schema_type(document: Mapping[str, Any], schema: Mapping[str, Any]) -> str:
    """Render a compact type without using specification description prose."""
    component = referenced_component(schema)
    resolved = resolve_schema(document, schema)
    if "enum" in resolved:
        return "integer enum"
    raw_type = resolved.get("type")
    if raw_type == "array":
        items = resolved.get("items", {})
        if isinstance(items, dict):
            return f"array<{schema_type(document, items)}>"
        return "array"
    if raw_type == "object" or "properties" in resolved:
        if component:
            return short_component_name(component)
        additional = resolved.get("additionalProperties")
        if isinstance(additional, dict):
            return f"object<string, {schema_type(document, additional)}>"
        return "object"
    if component:
        return short_component_name(component)
    schema_format = resolved.get("format")
    if isinstance(raw_type, str) and isinstance(schema_format, str):
        return f"{raw_type} ({schema_format})"
    return str(raw_type or "value")


def canonical_enum_name(schema: Mapping[str, Any], field_name: str) -> str | None:
    """Select the label table for one concrete enum occurrence."""
    component = referenced_component(schema)
    if component:
        canonical = canonical_enum_for_component(component)
        if canonical:
            return canonical
    return FIELD_ENUM_NAMES.get(field_name.replace("[]", "").lower())


def allowed_values(
    document: Mapping[str, Any],
    schema: Mapping[str, Any],
    field_name: str,
    enum_tables: Mapping[str, Mapping[int, str]],
) -> str:
    """Render exactly the enum subset carried by this operation's schema."""
    candidate = schema
    resolved = resolve_schema(document, candidate)
    if resolved.get("type") == "array" and isinstance(resolved.get("items"), dict):
        candidate = resolved["items"]
        resolved = resolve_schema(document, candidate)
    enum = resolved.get("enum")
    if not isinstance(enum, list):
        return "—"
    canonical = canonical_enum_name(candidate, field_name)
    labels = enum_tables.get(canonical or "", {})
    rendered: list[str] = []
    for value in enum:
        label = labels.get(value) if isinstance(value, int) else None
        rendered.append(f"`{value}` ({label})" if label else f"`{value}`")
    return ", ".join(rendered)


def flatten_schema(
    document: Mapping[str, Any],
    schema: Mapping[str, Any],
    enum_tables: Mapping[str, Mapping[int, str]],
    *,
    prefix: str = "",
    depth: int = 0,
    max_depth: int = 2,
    seen_components: frozenset[str] = frozenset(),
) -> list[SchemaRow]:
    """Flatten object fields enough to reveal useful nested request/response data."""
    component = referenced_component(schema)
    if component in seen_components:
        return []
    next_seen = seen_components | ({component} if component else set())
    resolved = resolve_schema(document, schema)

    if resolved.get("type") == "array":
        items = resolved.get("items")
        if isinstance(items, dict):
            item_prefix = f"{prefix}[]" if prefix else "items[]"
            return flatten_schema(
                document,
                items,
                enum_tables,
                prefix=item_prefix,
                depth=depth,
                max_depth=max_depth,
                seen_components=next_seen,
            )

    properties = resolved.get("properties")
    if not isinstance(properties, dict):
        field = prefix or "value"
        return [
            SchemaRow(
                field=field,
                type_name=schema_type(document, schema),
                required=True,
                nullable=bool(schema.get("nullable", resolved.get("nullable", False))),
                allowed_values=allowed_values(
                    document, schema, field.rsplit(".", 1)[-1], enum_tables
                ),
            )
        ]

    required_fields = set(resolved.get("required", []))
    rows: list[SchemaRow] = []
    for field_name, raw_field_schema in properties.items():
        if not isinstance(raw_field_schema, dict):
            continue
        field = f"{prefix}.{field_name}" if prefix else field_name
        field_schema = raw_field_schema
        field_resolved = resolve_schema(document, field_schema)
        rows.append(
            SchemaRow(
                field=field,
                type_name=schema_type(document, field_schema),
                required=field_name in required_fields,
                nullable=bool(
                    field_schema.get("nullable", field_resolved.get("nullable", False))
                ),
                allowed_values=allowed_values(
                    document, field_schema, field_name, enum_tables
                ),
            )
        )

        if depth >= max_depth:
            continue
        nested_schema: Mapping[str, Any] | None = None
        nested_prefix = field
        if field_resolved.get("type") == "array" and isinstance(
            field_resolved.get("items"), dict
        ):
            nested_schema = field_resolved["items"]
            nested_prefix += "[]"
        elif "properties" in field_resolved:
            nested_schema = field_schema
        if nested_schema is None:
            continue
        nested_resolved = resolve_schema(document, nested_schema)
        if not isinstance(nested_resolved.get("properties"), dict):
            continue
        rows.extend(
            flatten_schema(
                document,
                nested_schema,
                enum_tables,
                prefix=nested_prefix,
                depth=depth + 1,
                max_depth=max_depth,
                seen_components=next_seen,
            )
        )
    return rows


def markdown_cell(value: str) -> str:
    """Escape generated table content for Markdown."""
    return value.replace("|", "\\|").replace("\n", " ")


def render_schema_table(rows: Sequence[SchemaRow]) -> list[str]:
    """Render schema rows with the four required field characteristics."""
    if not rows:
        return ["No fields are defined in the snapshot."]
    rendered = [
        "| Field | Type | Required | Nullable | Allowed values |",
        "|---|---|:---:|:---:|---|",
    ]
    for row in rows:
        required = (
            "Unknown" if row.required is None else ("Yes" if row.required else "No")
        )
        nullable = (
            "Unknown" if row.nullable is None else ("Yes" if row.nullable else "No")
        )
        rendered.append(
            f"| `{markdown_cell(row.field)}` | `{markdown_cell(row.type_name)}` | "
            f"{required} | {nullable} | {markdown_cell(row.allowed_values)} |"
        )
    return rendered


def operation_parameters(operation: Operation) -> list[dict[str, Any]]:
    """Combine path-level and operation-level parameter definitions."""
    parameters: list[dict[str, Any]] = []
    for source in (
        operation.path_item.get("parameters", []),
        operation.definition.get("parameters", []),
    ):
        if not isinstance(source, list):
            raise ReferenceBuildError(
                f"parameters must be a list for {operation.method.upper()} {operation.path}"
            )
        for parameter in source:
            if not isinstance(parameter, dict):
                raise ReferenceBuildError(
                    f"parameter must be an object for {operation.method.upper()} {operation.path}"
                )
            parameters.append(parameter)
    return parameters


def request_content(operation: Operation) -> tuple[str, dict[str, Any]] | None:
    """Choose one structural request-body media type, preferring standard JSON."""
    request_body = operation.definition.get("requestBody")
    if not isinstance(request_body, dict):
        return None
    content = request_body.get("content")
    if not isinstance(content, dict) or not content:
        return None
    for media_type in (
        "application/json",
        "multipart/form-data",
        "application/*+json",
        "text/json",
    ):
        media = content.get(media_type)
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media_type, media["schema"]
    for media_type, media in content.items():
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media_type, media["schema"]
    return None


def response_content(response: Mapping[str, Any]) -> dict[str, Any] | None:
    """Choose one response schema without reading response description prose."""
    content = response.get("content")
    if not isinstance(content, dict):
        return None
    for media_type in ("application/json", "application/*+json", "text/json"):
        media = content.get(media_type)
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media["schema"]
    for media in content.values():
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media["schema"]
    return None


def request_rows(
    operation: Operation, enum_tables: Mapping[str, Mapping[int, str]]
) -> tuple[list[SchemaRow], str | None]:
    """Build parameter and body rows for one operation."""
    rows: list[SchemaRow] = []
    for parameter in operation_parameters(operation):
        name = parameter.get("name")
        location = parameter.get("in")
        schema = parameter.get("schema")
        if (
            not isinstance(name, str)
            or not isinstance(location, str)
            or not isinstance(schema, dict)
        ):
            raise ReferenceBuildError(
                f"malformed parameter for {operation.method.upper()} {operation.path}"
            )
        resolved = resolve_schema(operation.document, schema)
        rows.append(
            SchemaRow(
                field=f"{location}: {name}",
                type_name=schema_type(operation.document, schema),
                required=bool(parameter.get("required", False)),
                nullable=bool(schema.get("nullable", resolved.get("nullable", False))),
                allowed_values=allowed_values(
                    operation.document, schema, name, enum_tables
                ),
            )
        )

    body = request_content(operation)
    if body is None:
        return rows, None
    media_type, schema = body
    body_rows = flatten_schema(operation.document, schema, enum_tables)
    if operation.path == "/api/public/v1/persona" and operation.method in {
        "post",
        "put",
    }:
        # fact:persona-voiceid: live behavior establishes this as a returned
        # compatibility field, not a writable persona field. The snapshot
        # incorrectly includes it in both request DTOs.
        body_rows = [row for row in body_rows if row.field != "elevenLabsVoiceId"]
    rows.extend(
        SchemaRow(
            field=f"body: {row.field}",
            type_name=row.type_name,
            required=row.required,
            nullable=row.nullable,
            allowed_values=row.allowed_values,
        )
        for row in body_rows
    )
    return rows, media_type


def response_rows(
    operation: Operation,
    enum_tables: Mapping[str, Mapping[int, str]],
) -> list[tuple[str, list[SchemaRow]]]:
    """Build schema rows for each success response in the snapshot."""
    responses = operation.definition.get("responses")
    if not isinstance(responses, dict):
        raise ReferenceBuildError(
            f"responses must be an object for {operation.method.upper()} {operation.path}"
        )
    rendered: list[tuple[str, list[SchemaRow]]] = []
    for status, response in responses.items():
        if not str(status).startswith("2"):
            continue
        if not isinstance(response, dict):
            raise ReferenceBuildError(
                f"response {status} must be an object for {operation.method.upper()} {operation.path}"
            )
        if (
            operation.method == "get"
            and operation.path == "/api/public/v1/persona/voices"
            and str(status).startswith("2")
        ):
            # fact:persona-voiceid overrides the incorrect PublicPersonaDto
            # response reference in the snapshot. The verified fact establishes
            # field names, but not types or nullability, so those remain unknown.
            rows = [
                SchemaRow(field, "value", None, None, "—")
                for field in (
                    "items[].voiceId",
                    "items[].elevenLabsVoiceId",
                    "items[].voiceName",
                    "items[].gender",
                    "items[].age",
                )
            ]
        else:
            schema = response_content(response)
            rows = (
                flatten_schema(operation.document, schema, enum_tables)
                if schema is not None
                else []
            )
        rendered.append((str(status), rows))
    return rendered


def sample_scalar(schema: Mapping[str, Any], field_name: str) -> Any:
    """Return a neutral placeholder based only on schema shape and field name."""
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        return enum[0]
    schema_type_name = schema.get("type")
    lowered = field_name.lower()
    if schema_type_name == "integer":
        if lowered == "pagenumber":
            return 0
        if lowered == "pagesize":
            return 25
        return 123 if lowered.endswith("id") else 0
    if schema_type_name == "number":
        return 0.0
    if schema_type_name == "boolean":
        return False
    if schema_type_name == "string":
        schema_format = schema.get("format")
        if schema_format == "date-time":
            if lowered in {"start", "startdate", "from"}:
                return "2026-08-12T14:00:00Z"
            if lowered in {"end", "enddate", "to"}:
                return "2026-08-12T15:00:00Z"
            if "due" in lowered:
                return "2099-01-01T12:00:00Z"
            return "2026-08-12T15:00:00Z"
        if schema_format == "date":
            return "2099-01-01" if "due" in lowered else "2026-08-12"
        if schema_format in {"uri", "url"} or "url" in lowered:
            return "https://example.com/recording"
        if "email" in lowered:
            return "rep@example.com"
        if lowered in {"name", "title"} or lowered.endswith("name"):
            return "Example"
        return "string"
    return None


def sample_value(
    document: Mapping[str, Any],
    schema: Mapping[str, Any],
    *,
    field_name: str = "",
    depth: int = 0,
    seen_components: frozenset[str] = frozenset(),
) -> Any:
    """Build a small illustrative value from schema structure, never descriptions."""
    component = referenced_component(schema)
    resolved = resolve_schema(document, schema)
    if component in seen_components or depth > 4:
        if resolved.get("nullable") is True:
            return None
        if resolved.get("type") == "array":
            return []
        if resolved.get("type") == "object" or "properties" in resolved:
            return {}
        return sample_scalar(resolved, field_name)
    next_seen = seen_components | ({component} if component else set())
    if "enum" in resolved:
        return sample_scalar(resolved, field_name)
    if resolved.get("type") == "array":
        items = resolved.get("items")
        if not isinstance(items, dict):
            return []
        return [
            sample_value(
                document,
                items,
                field_name=field_name.removesuffix("s"),
                depth=depth + 1,
                seen_components=next_seen,
            )
        ]
    properties = resolved.get("properties")
    if isinstance(properties, dict):
        required = [name for name in resolved.get("required", []) if name in properties]
        priority = [
            "id",
            "name",
            "title",
            "email",
            "status",
            "pageNumber",
            "pageSize",
        ]
        selected = list(required)
        for name in priority:
            if name in properties and name not in selected:
                selected.append(name)
        for name in properties:
            if len(selected) >= 5:
                break
            if name not in selected:
                selected.append(name)
        return {
            name: sample_value(
                document,
                properties[name],
                field_name=name,
                depth=depth + 1,
                seen_components=next_seen,
            )
            for name in selected
            if isinstance(properties[name], dict)
        }
    return sample_scalar(resolved, field_name)


def sample_request_body(operation: Operation, schema: Mapping[str, Any]) -> Any:
    """Build a structural request example, with verified facts taking precedence."""
    if (
        operation.method == "patch"
        and operation.path == "/api/public/v1/scorecard/{id}/status"
    ):
        # fact:scorecard-publish-api is the canonical worked example for this route.
        return {"status": 1}
    sample = sample_value(operation.document, schema)
    if (
        operation.path == "/api/public/v1/persona"
        and operation.method in {"post", "put"}
        and isinstance(sample, dict)
    ):
        # Keep the worked payload aligned with fact:persona-voiceid too.
        sample.pop("elevenLabsVoiceId", None)
    return sample


def parameter_sample(
    operation: Operation, parameter: Mapping[str, Any]
) -> str | int | float | bool:
    """Create one path or query placeholder from a parameter schema."""
    schema = parameter.get("schema")
    name = str(parameter.get("name", "value"))
    if not isinstance(schema, dict):
        return "value"
    sample = sample_value(operation.document, schema, field_name=name)
    if isinstance(sample, (str, int, float, bool)):
        return sample
    return "value"


def operation_host(operation: Operation) -> str:
    """Use the verified practice-host exception only for evaluation ID routes."""
    if (
        operation.path == "/api/public/v1/evaluation/{evaluationId}"
        and operation.method
        in {
            "get",
            "delete",
        }
    ):
        return PRACTICE_HOST
    return GATEWAY_HOST


def curl_example(operation: Operation) -> list[str]:
    """Render a runnable curl shape that references, but never prints, the key."""
    path = operation.path
    query: list[tuple[str, Any]] = []
    for parameter in operation_parameters(operation):
        location = parameter.get("in")
        name = parameter.get("name")
        if not isinstance(name, str):
            continue
        value = parameter_sample(operation, parameter)
        if location == "path":
            path = path.replace("{" + name + "}", str(value))
        elif location == "query" and parameter.get("required"):
            query.append((name, value))
    url = f"{operation_host(operation)}{path}"
    if query:
        url += "?" + urlencode(query)

    command = [
        "curl --fail-with-body --silent --show-error \\",
        f"  --request {operation.method.upper()} \\",
        '  --header "X-API-Key: $ITERO_API_KEY" \\',
    ]
    body = request_content(operation)
    if body is not None:
        media_type, schema = body
        if media_type == "multipart/form-data":
            command.append("  --form 'file=@users.csv;type=text/csv' \\")
        else:
            payload = json.dumps(
                sample_request_body(operation, schema), ensure_ascii=False, indent=2
            )
            payload_lines = payload.splitlines()
            command.append('  --header "Content-Type: application/json" \\')
            if len(payload_lines) == 1:
                command.append(f"  --data '{payload}' \\")
            else:
                command.append(f"  --data '{payload_lines[0]}")
                command.extend(f"{line}" for line in payload_lines[1:-1])
                command.append(f"{payload_lines[-1]}' \\")
    output_file = SAFE_OUTPUT_FILES.get((operation.method, operation.path))
    if output_file:
        command.append(f'  "{url}" \\')
        command.append(f'  --output "{output_file}"')
    else:
        command.append(f'  "{url}"')
    return command


def successful_codes(operation: Operation) -> str:
    """Return success response codes listed structurally in the operation."""
    responses = operation.definition.get("responses", {})
    if not isinstance(responses, dict):
        return "—"
    codes = [f"`{status}`" for status in responses if str(status).startswith("2")]
    return ", ".join(codes) or "—"


def error_rows(operation: Operation) -> list[tuple[str, str]]:
    """Return generic meanings for error codes that the snapshot lists."""
    responses = operation.definition.get("responses", {})
    if not isinstance(responses, dict):
        return []
    rows: list[tuple[str, str]] = []
    for raw_status in responses:
        status = str(raw_status)
        if status.startswith("2"):
            continue
        rows.append((status, ERROR_MEANINGS.get(status, ERROR_MEANINGS["default"])))
    return rows


def render_operation(
    operation: Operation, enum_tables: Mapping[str, Mapping[int, str]]
) -> list[str]:
    """Render one complete operation reference."""
    method = operation.method.upper()
    lines = [f"### `{method} {operation.path}`", "", "#### Request schema", ""]
    request, media_type = request_rows(operation, enum_tables)
    if request:
        lines.extend(render_schema_table(request))
        if media_type:
            lines.extend(["", f"Body media type: `{media_type}`."])
    else:
        lines.append("This operation has no parameters or request body.")

    output_file = SAFE_OUTPUT_FILES.get((operation.method, operation.path))
    if operation.method == "get":
        example_guidance = (
            "Replace the example identifier or query value, then run this read request."
        )
    else:
        example_guidance = (
            "Show this exact payload to the user and wait for explicit confirmation "
            "before running the request."
        )
    if output_file:
        example_guidance += (
            f" The raw response is saved to `{output_file}`; project only the fields "
            "you need before bringing any result into the conversation."
        )
    lines.extend(
        [
            "",
            "#### Example",
            "",
            example_guidance,
            "",
            "```bash",
            *curl_example(operation),
            "```",
            "",
            "#### Success response schema",
            "",
        ]
    )
    successes = response_rows(operation, enum_tables)
    if not successes:
        lines.append("The snapshot does not list a success response.")
    for index, (status, rows) in enumerate(successes):
        if index:
            lines.append("")
        lines.append(f"Status `{status}`:")
        lines.append("")
        if (
            operation.method == "get"
            and operation.path == "/api/public/v1/persona/voices"
        ):
            lines.extend(
                [
                    "Verified-fact override: the snapshot incorrectly points this response to the persona schema. Live verification established the five fields below. It did not establish their types, required status, or nullability, so those cells remain unknown.",
                    "",
                ]
            )
        if rows:
            lines.extend(render_schema_table(rows))
        else:
            lines.append("The response has no body.")

    lines.extend(["", "#### Error responses", ""])
    errors = error_rows(operation)
    if errors:
        lines.extend(["| Status | Meaning |", "|---:|---|"])
        lines.extend(f"| `{status}` | {meaning} |" for status, meaning in errors)
    else:
        lines.append("The snapshot does not list an error response for this operation.")
    return lines


def render_reference(
    config: OutputConfig,
    operations: Sequence[Operation],
    shared_notes: str,
    enum_tables: Mapping[str, Mapping[int, str]],
) -> str:
    """Render one complete skill reference from structural and curated sources."""
    shared_gotchas = extract_marked_block(
        shared_notes, "gotchas", NOTES_DIR / "_shared.md"
    )
    if shared_gotchas is None:
        raise ReferenceBuildError("notes/_shared.md is missing its gotchas block")
    resource_notes = read_text(config.note_path)
    resource_gotchas = extract_marked_block(resource_notes, "gotchas", config.note_path)
    resource_lifecycle = extract_marked_block(
        resource_notes, "lifecycle", config.note_path
    )
    if resource_gotchas is None:
        raise ReferenceBuildError(
            f"{relative(config.note_path)} is missing its gotchas block"
        )

    lines = [
        GENERATED_HEADER.format(note=relative(config.note_path)),
        "",
        f"# {config.title}",
        "",
        "This reference is generated from the committed OpenAPI 3.0.1 snapshots. Schema tables use only `paths` and `components.schemas`; curated behavior comes from the marked notes blocks below.",
        "",
        "Use the gateway host unless an operation is explicitly marked as using the practice host. Read the API key from `ITERO_API_KEY` and never print it.",
        "",
        "## Verified guidance",
        "",
        shared_gotchas,
        "",
        resource_gotchas,
    ]
    if resource_lifecycle:
        lines.extend(["", resource_lifecycle])

    lines.extend(
        [
            "",
            "## Endpoint map",
            "",
            "| Method | Path | Host | Success |",
            "|---|---|---|---|",
        ]
    )
    for operation in operations:
        host_name = (
            "Practice host" if operation_host(operation) == PRACTICE_HOST else "Gateway"
        )
        lines.append(
            f"| `{operation.method.upper()}` | `{operation.path}` | {host_name} | {successful_codes(operation)} |"
        )

    lines.extend(["", "## Operations", ""])
    for index, operation in enumerate(operations):
        if index:
            lines.extend(["", "---", ""])
        lines.extend(render_operation(operation, enum_tables))
    return "\n".join(lines).rstrip() + "\n"


def validate_generated_facts(
    facts: Iterable[Mapping[str, Any]], rendered: Mapping[Path, str]
) -> None:
    """Require every manifested marker in every listed generated output."""
    for fact in facts:
        fact_id = str(fact["id"])
        marker = f"<!-- {fact_id} -->"
        for raw_output in fact["outputs"]:
            output = safe_repo_path(str(raw_output), source=fact_id)
            content = rendered.get(output)
            if content is None:
                raise ReferenceBuildError(
                    f"marker {fact_id} names output that was not generated: {raw_output}"
                )
            if marker not in content:
                raise ReferenceBuildError(
                    f"missing marker {fact_id} in generated output {raw_output}"
                )


def validate_fact_overrides(rendered: Mapping[Path, str]) -> None:
    """Keep operation-specific fact overrides from drifting back to bad spec data."""
    personas_path = OUTPUTS["personas"].path.resolve()
    personas = rendered[personas_path]
    if "`body: elevenLabsVoiceId`" in personas:
        raise ReferenceBuildError(
            "fact:persona-voiceid: persona write schemas must not expose "
            "elevenLabsVoiceId"
        )


def build_outputs() -> tuple[dict[Path, str], int, int]:
    """Load, validate, route, and render every reference fully in memory."""
    specs = load_specs()
    shared_notes = read_text(NOTES_DIR / "_shared.md")
    enum_tables = parse_enum_tables(shared_notes)
    validate_enum_tables(specs, enum_tables)
    facts = load_and_validate_facts()
    operations, suppressed = collect_operations(specs)

    rendered = {
        config.path.resolve(): render_reference(
            config, operations[key], shared_notes, enum_tables
        )
        for key, config in OUTPUTS.items()
    }
    validate_generated_facts(facts, rendered)
    validate_fact_overrides(rendered)
    documented_count = sum(len(items) for items in operations.values())
    return rendered, documented_count, len(suppressed)


def check_outputs(rendered: Mapping[Path, str]) -> bool:
    """Regenerate into a temporary tree and print diffs from committed outputs."""
    clean = True
    with tempfile.TemporaryDirectory(prefix="itero-refs-check-") as temporary:
        temporary_root = Path(temporary)
        for destination, content in rendered.items():
            staged = temporary_root / relative(destination)
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(content, encoding="utf-8")

        for destination in sorted(rendered, key=relative):
            staged = temporary_root / relative(destination)
            expected = staged.read_text(encoding="utf-8").splitlines(keepends=True)
            try:
                actual = destination.read_text(encoding="utf-8").splitlines(
                    keepends=True
                )
            except FileNotFoundError:
                actual = []
            except OSError as exc:
                raise ReferenceBuildError(
                    f"could not read {relative(destination)}: {exc}"
                ) from exc
            if actual == expected:
                continue
            clean = False
            diff = difflib.unified_diff(
                actual,
                expected,
                fromfile=relative(destination),
                tofile=f"generated/{relative(destination)}",
            )
            sys.stdout.writelines(diff)
    return clean


def replace_outputs(rendered: Mapping[Path, str]) -> None:
    """Stage all outputs, then atomically replace each destination with rollback."""
    staged: dict[Path, Path] = {}
    originals: dict[Path, bytes | None] = {}
    replaced: list[Path] = []

    try:
        for destination, content in rendered.items():
            destination.parent.mkdir(parents=True, exist_ok=True)
            originals[destination] = (
                destination.read_bytes() if destination.exists() else None
            )
            descriptor, temporary_name = tempfile.mkstemp(
                dir=destination.parent,
                prefix=f".{destination.name}.",
                suffix=".tmp",
            )
            temporary_path = Path(temporary_name)
            staged[destination] = temporary_path
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            temporary_path.chmod(0o644)

        for destination in sorted(staged, key=relative):
            os.replace(staged[destination], destination)
            replaced.append(destination)
    except OSError as exc:
        rollback_errors: list[str] = []
        for destination in reversed(replaced):
            try:
                original = originals[destination]
                if original is None:
                    destination.unlink(missing_ok=True)
                else:
                    descriptor, temporary_name = tempfile.mkstemp(
                        dir=destination.parent,
                        prefix=f".{destination.name}.rollback.",
                        suffix=".tmp",
                    )
                    with os.fdopen(descriptor, "wb") as handle:
                        handle.write(original)
                        handle.flush()
                        os.fsync(handle.fileno())
                    os.replace(temporary_name, destination)
            except OSError as rollback_exc:
                rollback_errors.append(f"{relative(destination)}: {rollback_exc}")
        details = f"failed to replace generated references: {exc}"
        if rollback_errors:
            details += "; rollback also failed for " + "; ".join(rollback_errors)
        raise ReferenceBuildError(details) from exc
    finally:
        for temporary_path in staged.values():
            temporary_path.unlink(missing_ok=True)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse the drift-check mode."""
    parser = argparse.ArgumentParser(
        description="Generate API references from committed Itero OpenAPI snapshots."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated references without changing files",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Build or verify all generated API references."""
    args = parse_args(argv)
    try:
        rendered, documented_count, suppressed_count = build_outputs()
        if args.check:
            if not check_outputs(rendered):
                print(
                    "error: generated references are out of date; run uv run tools/build-refs.py",
                    file=sys.stderr,
                )
                return 1
            print(f"checked {len(rendered)} generated references")
        else:
            replace_outputs(rendered)
            for destination in sorted(rendered, key=relative):
                print(f"generated {relative(destination)}")
        print(
            f"classified {documented_count + suppressed_count} operations: "
            f"{documented_count} documented, {suppressed_count} canonical alias suppressed"
        )
        return 0
    except ReferenceBuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
